Update feed.py
- Error: CbFeed.__init__() got an unexpected keyword argument 'strict'

Added 'strict' object to line 528 that is provided on the class function call line 94 of validate_feed.py 

- Error: Feed `x` is invalid: Problem with feed `Bad Report`, report `668`: name 'query' is not defined

Line 378, only checks for it being a dictionary, however the documentation states this should be dictionaries within a list. This causes a failure on query based validations. [{'index_type': 'events', 'search_query': 'cb.urlver=1&q=process_name%3Achrome.exe'}]

- Error: Feed `x` is invalid: Problem with feed `Feed Tester`, report `chrome_proc`: 'list' object has no attribute 'keys'
line 401 is getting snagged on no keys, again json get's sent as a list of dictionaries. Corrected by adding [0]

- Error: Feed `x` is invalid: Problem with feed `Feed Tester`, report `chrome_proc`: Report 'chrome_proc', field 'iocs', 'query' has bad 'search_query': c
Line 420-422, code is treating it as a dictionary and instead iterates the letters.  Also added a search_query key check to ignore the "index_type" key from the other dictionary.

-  Line 424, checks for "q=" and "cb.q.". As of 6.3.0+, watchlist_searcher requires the query to start with q= or cb.urlver=1&q=. The search job will fail when starting with cb.q.alliance_score_abuse= for example. Updated the code to look for the correct start of a search query and provide better messaging on the error report

- Line 514, added search_query to the error report output for the user to see which query is causing the issue.